### ISSUE TITLE
FR master needs several seconds for loading articles

### ISSUE THREAD

**Issue by fbruetting** [jangernert/FeedReader#238]
Branch: master & articleview

• When FR is opened, no articles are displayed though „all articles“ is selected.
• When I select a feed, CPU load goes up in correlation with the number of contained articles (forever).
   – No articles: ~ 1-2 %
   – 4 articles: ~ 3 %
   – 11 articles: ~ 5 %
   – 31 articles: ~ 6 %
   – 25 articles: ~ 90 % (Feed: Curved)
   – all articles (143): ~ 100 %
• As you see in the GIF, everytime I select a list, the articles need a lot of time for loading. This wasn't the case before. The overall performance is reduced, too. I see two bugs there: One article-related CPU load bug and one with the curved.de feed.

![fr](https://cloud.githubusercontent.com/assets/10520767/19250382/38ba46b0-8f3a-11e6-9813-54ee5f5d988d.gif)

**Comment by fb87** [comment]
Branch: master

Somehow, the list consists of just a few articles, so it gets empty without being really empty, see screenshot:

![auswahl_010](https://cloud.githubusercontent.com/assets/10520767/19252449/33659ab0-8f45-11e6-94f2-dfb82e352df1.png)

**Comment by jangernert** [comment]
Well, it's pretty normal that creating ~150 complex widgets isn't instant. The question is why is your row offset so high.
Is your build up to date?

**Comment by fb87** [comment]
Latest build, but I already had almost 2000 news articles and it ran WAY better. Especially with Curved, there seems to be a slowdown.

**Comment by jangernert** [comment]
When you start at the top of the list, FeedReader doesn't actually create all the widgets.
It only creates enough to fill the view and loads more once the list scrolls down.

**Comment by fb87** [comment]
In master new ones aren't getting created until I switch feeds and switch back. But wouldn't it be ok to create all widgets per feed? They're just 5 lines of text and the rest of the articles doesn't need to be loaded.

**Comment by jangernert** [comment]
No, that's not an option. The widget is way more complex than you think. And even if it was simpler, creating 2000 ListBoxRows still wouldn't be fast.
Btw: update to head again. c41cf077c982632dee47a18c3cabbcec1edc6d72

**Comment by fb87** [comment]
Ok, I'll do. It felt way faster with 1.6 though and didn't produces as near as much cpu load.

**Comment by fb87** [comment]
New bug:
// Still no german interface

![peek 2016-10-13 01-17](https://cloud.githubusercontent.com/assets/10520767/19331105/e78600a4-90e2-11e6-8f47-4f7ea8848464.gif)

**Comment by jangernert** [comment]
Soooo... how would I reproduce this? I turned off "newest articles first", switched to "unread"-mode and had 4 unread articles total. When I switch from an empty feed to "all articles" everything works fine.

**Comment by fb87** [comment]
Today after fetching new articles, this didn't happen again… yet.
But as always: I push update (if not done automatically) and read the articles – and sometimes there are side effects. No way to reproduce.

**Comment by jangernert** [comment]
The double articles should be fixed. Latest commit in master is kind of an experiment: lazyloading also to the top. This however has the drawback that you can't immediately scroll to the very top of the list right after starting the application as the articles are gradually loaded as the users scrolls up. (only affects columns other than "unread")

**Comment by fb87** [comment]
• The load situation is now better with going up to 20% for some seconds if another feed is selected, then it drops to relatively constant 10% – something must be running, although the application shouldn't do anything.
• The problem with not all articles being displayed still exists. I have to switch to another feed and back again for all articles being displayed. Maybe it's due to some newer articles getting fetched while the feed is already displayed and they are not loaded into the current article list?
• The repeatedly duplicate appearance of some articles still existed some days ago, but I haven't really tested your latest commits, maybe it's gone now. No idea how to reproduce, sometimes it happens and I have no clue why so…
• I can see no difference between the day before yesterday's commit and today's commit, but recognized that loaded articles (after scrolling action) get trashed, when scrolling back – so they have to be reloaded when scrolling again. Is this intended or a bug?

**Comment by fb87** [comment]
Now the repeated reappearing article issue happened again and caused the program to crash. Maybe you can find some information in my logs. Happened in the middle of working through my unread (all articles) list.

[feedreader.tar.gz](https://github.com/jangernert/FeedReader/files/620640/feedreader.tar.gz)
