### ISSUE TITLE
Serving of blank pages once 'api_feedreader' plugin is enabled

### ISSUE THREAD

**Issue by jhaye** [jangernert/FeedReader#752]
Enabling the `api_feedreader` plugin in `config.php` of TT-RSS results in it to exclusively serve empty pages. Removing it returns everything back to normal.

TT-RSS version: 1.17.4
Database type: pgsql

I have no idea how to troubleshoot this, any hints would be greatly appreciated.

**Comment by jhaye** [comment]
It appears this has something to do with the change that was made a few days ago.
Reverting it results in everything working as expected.

**Comment by brendanlong** [comment]
Are you saying we should revert 77915b12dc17d81f0147d308c7884f62e4319e99?

**Comment by brendanlong** [comment]
Thanks for the info :\

**Comment by pixolin** [comment]
> I was running a tt-rss version from last year, so I upgraded to the new one.

Did you check the PHP version running on your server? 
> "You will need PHP 5.6 (or newer, PHP 7 is fine) compiled with the following modules ... PDO with support for PostgreSQL or MySQL depending on the database ..."
(PhpCompatibilityNotes - Tiny Tiny RSS)[https://git.tt-rss.org/fox/tt-rss/wiki/PhpCompatibilityNotes]

**Comment by jhaye** [comment]
@pixolin Yes, it is running PHP 7.0.30

**Comment by pixolin** [comment]
@jhaye … sorry for insisting: have you checked if the PDO module was activated, too?
Just trying to rule out some potential error sources.

**Comment by jhaye** [comment]
@pixolin No reason to be sorry at all.
It turns out that the PDO module was not enabled, and using that resulted in FeedReader not crashing anymore.

However it still couldn't fetch from the API giving me this error: 
`(feedreader:3): feedreader-CRITICAL **: 13:36:43.450: invalid ttrss session id`
`(feedreader:3): feedreader-CRITICAL **: 13:36:43.450: ttrss api error`

So I logged out and am now trying to reconnect with FeedReader, however on trying to log in it returns a `Please enter a valid password` error message with this error message in the console:
`(feedreader:3): feedreader-CRITICAL **: 13:47:14.369: Password.setPassword: Cannot create an item in a locked collection`

My Android client for tt-rss still works fine.

**Comment by jangernert** [comment]
`Password.setPassword: Cannot create an item in a locked collection`
Suggests that the problem lies with your keyring.
FeedReader saves passwords via libsecret which in turn uses gnome-keyring (or any other compatible implementation). Obviously you can't read or write to a keyring if it isn't unlocked. I think gnome unlocks the keyring as soon as you login via password. No idea how it works on other desktops.

**Comment by jhaye** [comment]
You are right, I'm currently using i3 for work purposes.
Though I could swear that I used FeedReader in i3 just yesterday and it worked fine.
Anyway I'll try to get this working properly this evening.

I'd say all of my issues are resolved, thanks for the advice and answering so quickly!

**Comment by jhaye** [comment]
Okay, so I tried setting everything up now, but the crash persists. I am able to log in, but when I let FeedReader sync with the server it crashes. Here is an excerpt from the command line:

```** (feedreader:3): CRITICAL **: 19:51:38.316: feed_reader_article_getHTML: assertion 'self != NULL' failed

** (feedreader:3): CRITICAL **: 19:51:38.316: feed_reader_article_getHTML: assertion 'self != NULL' failed

** (feedreader:3): CRITICAL **: 19:51:38.316: string_replace: assertion 'self != NULL' failed

** (feedreader:3): CRITICAL **: 19:51:38.316: feed_reader_article_setHTML: assertion 'self != NULL' failed

** (feedreader:3): CRITICAL **: 19:51:38.317: feed_reader_article_getDate: assertion 'self != NULL' failed

(feedreader:3): GLib-CRITICAL **: 19:51:38.317: g_date_time_difference: assertion 'end != NULL' failed

** (feedreader:3): CRITICAL **: 19:51:38.318: feed_reader_article_getDate: assertion 'self != NULL' failed

(feedreader:3): GLib-CRITICAL **: 19:51:38.318: g_date_time_difference: assertion 'end != NULL' failed

** (feedreader:3): CRITICAL **: 19:51:38.318: feed_reader_article_getArticleID: assertion 'self != NULL' failed

** (feedreader:3): CRITICAL **: 19:51:38.318: feed_reader_article_getFeedID: assertion 'self != NULL' failed

** (feedreader:3): CRITICAL **: 19:51:38.318: feed_reader_article_getURL: assertion 'self != NULL' failed

** (feedreader:3): CRITICAL **: 19:51:38.318: feed_reader_article_getUnread: assertion 'self != NULL' failed

** (feedreader:3): CRITICAL **: 19:51:38.318: feed_reader_article_getMarked: assertion 'self != NULL' failed

** (feedreader:3): CRITICAL **: 19:51:38.318: feed_reader_article_getTitle: assertion 'self != NULL' failed

(feedreader:3): feedreader-WARNING **: 19:51:38.318: Utils.UTF8fix: string is NULL

** (feedreader:3): CRITICAL **: 19:51:38.318: feed_reader_article_getHTML: assertion 'self != NULL' failed

** (feedreader:3): CRITICAL **: 19:51:38.318: feed_reader_article_getPreview: assertion 'self != NULL' failed

(feedreader:3): feedreader-WARNING **: 19:51:38.318: Utils.UTF8fix: string is NULL

** (feedreader:3): CRITICAL **: 19:51:38.318: feed_reader_article_getAuthor: assertion 'self != NULL' failed

** (feedreader:3): CRITICAL **: 19:51:38.319: feed_reader_article_getDate: assertion 'self != NULL' failed
Error while executing 'addr2line -f -e /app/bin/feedreader 0x7f9630f90c5c': Failed to execute child process “addr2line” (No such file or directory)
Something went very wrong. Your stacktrace cannot be displayed
An error occured (SIGSEGV)
```

**Comment by brendanlong** [comment]
Can you try again with v2.8.0? I made quite a few improvements to our TT-RSS plugin (both the FeedReader account plugin and the api_feedreader TT-RSS plugin). The crash you're getting looks like one that should be fixed by a52474a7fea023abc6ff9b873db6a0067f091254.

(Please re-open this if your problem isn't solved!)

**Comment by jhaye** [comment]
So I updated the plugin on my server and got Feedreader from Flathub. And while it doesn't crash anymore, it just kept syncing forever, hogging on my resources until I had no disk space left anymore and my system panicked.

**Comment by brendanlong** [comment]
Hm I'm not really sure what's going on here. Can you tell me more about the installation? Are you using the latest TT-RSS? Which database is TT-RSS connecting to (unfortunately this matters because of some problems in TT-RSS's API)?

Are you getting any errors in your TT-RSS logs?

If you close FeedReader with ctrl+q and then run it from the command-line (`flatpak run org.gnome.FeedReader`), are there any errors in the logs now?

**Comment by brendanlong** [comment]
Oh I see you answered some of them above. I was testing using TT-RSS v18.12 using the pgsql backend and it worked for me. One other thing is that maybe you have a lot more feeds than I do? I can try to get an OPML import working to see what happens if I add all of my normal feeds (I don't usually use TT-RSS).

**Comment by brendanlong** [comment]
I imported my entire set of feeds and ran into an issue that caused an infinite loop. It should be fixed in 193ea1291c6135f5357e6a9a340f323b49defbad and I'll start another release now.

**Comment by brendanlong** [comment]
I just started a v2.8.2 release on Flathub that should fix this. Please let me know if you're still seeing this problem afterward. At this point the TT-RSS backend works for me even if I import my (fairly substantial) feed list.

**Comment by jhaye** [comment]
Yes it's working now, thank you!
