### ISSUE TITLE
Articles from scienceblogs.de are incomplete

### ISSUE THREAD

**Issue by naraesk** [jangernert/FeedReader#878]
Using ArchLinux FeedReader 2.8.1 

Example article: http://scienceblogs.de/astrodicticum-simplex/2019/01/08/eine-revolution-alle-5-minuten-albert-einstein-ueber-schlechten-wissenschaftsjournalismus

FeedReader only shows a part of the article. Have the same problem with many other articles from scienleblogs. It seems that every article is cut off after three paragraphs.

**Comment by psukys** [comment]
It's how they serve their RSS of their articles.
Check [their RSS link](http://scienceblogs.de/astrodicticum-simplex/feed/atom/)

**Comment by naraesk** [comment]
What exactly do you mean?

Let's take the most recent article: http://scienceblogs.de/astrodicticum-simplex/2019/02/14/ein-schwarzes-loch-schluckt-einen-stern/

The last sentence shown by FeedReader is "Zuvor wird es durch die schnelle Bewegung aber noch stark aufgeheizt und strahlt sehr hell." However in the RSS link you postet many more sentences/paragraphs are following after this sentence (e.g. "Genau das hatte man 2014 beobachtet")

**Comment by brendanlong** [comment]
I assume you're using the local plugin?

**Comment by naraesk** [comment]
yes

**Comment by brendanlong** [comment]
It works for me if I use http://scienceblogs.de/astrodicticum-simplex/feed/atom/:

![screenshot from 2019-02-14 19-46-17](https://user-images.githubusercontent.com/1447206/52827057-3ccd7600-3091-11e9-94fb-1c0494284101.png)

**Comment by naraesk** [comment]
How can I find out which URL i used? I can right click on an entry and choose "copy URL", but nothing is copied to the clipboard. But probably I used http://scienceblogs.de/astrodicticum-simplex/feed/

**Comment by brendanlong** [comment]
Copying the URL of a feed should work in the latest version. Which plugin backend are you using?

**Comment by naraesk** [comment]
Local RSS

**Comment by brendanlong** [comment]
In v2.9.0 I added some fixes for local feed parsing, so it would be helpful if you could try that version. If it still has problems (with new articles), can you copy the feed URL (which should work now)?

**Comment by brendanlong** [comment]
I added http://scienceblogs.de/astrodicticum-simplex/feed/ using the local plugin and it seems to be showing full content for me. Please let me know if this is still not working for you in v2.9.0 though.

**Comment by naraesk** [comment]
Sorry for my late response. In the meantime I have updated to v2.9.2 (using the [this](https://www.archlinux.org/packages/community/x86_64/feedreader/) package). However, nothing has changed. Copy url does still not work and I still have the same problem with http://scienceblogs.de/astrodicticum-simplex/feed/
